apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ean-search-agent
  annotations:
    github.com/project-slug: miguelop00/ean-search-agent
  tags:
    - python
  links:
    - url: https://localhost:8000/docs
      title: LocalHost
spec:
  type: microservice
  lifecycle: development
  owner: miguelop00
